openapi: 3.0.0
info:
  title: 4DESA
  version: 1.0.0
  description: |-
    Link Up est une startup qui vise à fournir une plateforme de médias sociaux flexible aux créateurs de contenu. Ce système backend évolutif et efficace peut être intégré à n'importe quelle interface frontale, offrant une expérience de gestion de contenu transparente.La plateforme de Link Up répond à la demande croissante de solutions de médias sociaux personnalisables et évolutives dans l'espace du contenu numérique.

        Les Identifiants seront visibles lors du READ des entités
paths:
  /media/read:
    get:
      summary: Récupérer tous les médias
      tags:
        - Media
      responses:
        '200':
          description: Retourne la liste de média
  /media/create:
    post:
      summary: Créer un média
      tags:
        - Media
      
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
             type: object
             properties:
              image:
                type: object
                description: Insérer l'image
              titre:
                type: string
                description: Titre du média
              description:
                type: string
                description: Description du média
      
      responses:
        '201':
          description: Le fichier a été téléchargé avec succès.
        '400':
          description: Veuillez fournir un fichier.
        '500':
          description: Erreur serveur

  /media/update/{id}:
    put:
      summary: Mettre à jour un média
      tags:
        - Media
      parameters:
        - in: path
          name: id
          description: ID du média à mettre à jour
          required: true
          schema:
            type: string
      requestBody:
        required: false
        content:
          application/json:
            schema:
             type: object
             properties:
              titre:
                type: string
                description: Titre du média
              description:
                type: string
                description: Description du média
      responses:
        '200':
          description: Média mis à jour avec succès
        '400':
          description: Vous n'avez pas les droits de modifier ce média
        '404':
          description: Média non trouvé
        '500':
          description: Erreur Serveur
  /media/delete/{id}:
    delete:
      summary: Supprimer un média
      tags:
        - Media
      parameters:
        - in: path
          name: id
          description: ID du média à supprimer
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Retourne le média supprimé
        '400':
          description: Vous n'avez pas les droits de supprimer ce média
        '404':
          description: Média non trouvé
        '500':
          description: Erreur Serveur
          
  /user/read:
    get:
      summary: Récupérer tous les users
      tags:
        - User
      responses:
        '200':
          description: Retourne la liste de user
  /user/create:
    post:
      summary: Créer un utilisateur
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                 type: string
                 description: Mail de l'utilisateur
                pseudo:
                 type: string
                 description: Pseudo de l'utilisateur
                password:
                 type: string
                 description: Mot de passe de l'utilisateur
                priv:
                  type: boolean
                  description: Définit si le profil est privé ou public
      responses:
        '201':
          description: Créé avec succès
        '404':
          description: Vos informations entrées sont incorrectes
  
  /user/authentification:
    post:
      summary: Authentifier un utilisateur
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pseudo:
                 type: string
                 description: Pseudo de l'utilisateur
                password:
                 type: string
                 description: Mot de passe de l'utilisateur
      responses:
        '200':
          description: Authentification réussie
        '400':
          description: Mot de passe incorrect / Utilisateur inexistant / en attente du nom d'utilisateur et du mot de passe
          
  /user/update/{id}:
    put:
      summary: Mettre à jour un user
      tags:
        - User
      parameters:
        - in: path
          name: id
          description: ID du user à mettre à jour
          required: true
          schema:
            type: string
      requestBody:
        required: false
        content:
          application/json:
            schema:
             type: object
             properties:
                email:
                 type: string
                 description: Mail de l'utilisateur
                pseudo:
                 type: string
                 description: Pseudo de l'utilisateur
                password:
                 type: string
                 description: Mot de passe de l'utilisateur
      responses:
        '200':
          description: user mis à jour avec succès
        '403':
          description: Vous ne disposez pas des droits pour modifier cette personne
        '404':
          description: user non trouvé        
  /user/delete/{id}:
    delete:
      summary: Supprimer un user
      tags:
        - User
      parameters:
        - in: path
          name: id
          description: ID du user à supprimer
          required: true
          schema:
            type: string
      responses:
        '204':
          description: User supprimé avec succès
        '403':
          description: Vous ne disposez pas des droits pour supprimer cette personne
        '404':
          description: User non trouvé
